// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_aes_key`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

AccountKeys createAccount() => RustLib.instance.api.crateApiCreateAccount();

Uint8List encrypt(
        {required List<int> theirSignedPrekey, required List<int> plaintext}) =>
    RustLib.instance.api.crateApiEncrypt(
        theirSignedPrekey: theirSignedPrekey, plaintext: plaintext);

Uint8List decrypt(
        {required List<int> mySignedPrekeySecret,
        required List<int> ciphertext}) =>
    RustLib.instance.api.crateApiDecrypt(
        mySignedPrekeySecret: mySignedPrekeySecret, ciphertext: ciphertext);

class AccountKeys {
  final Uint8List identityKey;
  final Uint8List identitySecret;
  final Uint8List signedPrekey;
  final Uint8List signedPrekeySecret;

  const AccountKeys({
    required this.identityKey,
    required this.identitySecret,
    required this.signedPrekey,
    required this.signedPrekeySecret,
  });

  @override
  int get hashCode =>
      identityKey.hashCode ^
      identitySecret.hashCode ^
      signedPrekey.hashCode ^
      signedPrekeySecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountKeys &&
          runtimeType == other.runtimeType &&
          identityKey == other.identityKey &&
          identitySecret == other.identitySecret &&
          signedPrekey == other.signedPrekey &&
          signedPrekeySecret == other.signedPrekeySecret;
}
