// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: flutter pub run build_runner build
// (Generated by drift_dev)

part of 'conversations_dao.dart';

// Stub - will be generated by build_runner when flutter is installed
