// GENERATED CODE - DO NOT MODIFY BY HAND
// Run: flutter pub run build_runner build
// (Generated by json_serializable)
part of 'messages.dart';

// Stub - will be generated by build_runner when flutter is installed
// All fromJson/toJson implementations go here
